### ISSUE TITLE
Validation conflicts with multiple forms

### ISSUE THREAD

**Issue by pvien027** [draganbabic/uni-form#16]
First off I'm new to github so sorry if I'm posting this on the wrong section of this project. But I've noticed a specific behavior that should be revised. When declaring two uni-form's on a page, on the submit of one form, both forms are validated. This means that pages with a register and login form (for example) will not pass validation unless all registration and login infos are added. 

A simple fix would be to scope down the validation (and search of inputs) to the focuses form instead of the entire page. Should also make the validation more efficient. 

I don't dare making the change myself because I don't know if i can/don't know how :) Again, please let me know if I should submit this somewhere else.

Thanks.

**Comment by draganbabic** [comment]
Thanks for the report, I've forwarded it to Craig, who is maintaining the JS part of Uni–Form.
